### ISSUE TITLE
Security issue: no authentication for ReCharge customer portal

### ISSUE THREAD

**Issue by bcbweb** [ScreenStaring/recharge-api#2]
I've mentioned this previously in the Slack channel, but I'd like to flag this more publicly too. There doesn't appear to be any authentication happening for the ReCharge customer portal. So given someone's customer ID and nothing else (0-factor) I can gain full access to another customer's portal, allowing me to view personal information and even incur costs such as adding products to their subscription. This portal should be hooked in with Shopify's user authentication.

To reproduce, log in as a user to a Shopify store using ReCharge and access the customer portal. Copy the URL for this page, open a new incognito browser window and paste the URL. We can now access that user's account without ever having logged in. The customer ID is random and difficult to guess but could be easily leaked, so this is really not acceptable.

I would like to know when ReCharge intends on fixing this, as both my client and I consider this to be a serious concern.

**Comment by bcbweb** [comment]
Closing this - am unclear on who is actually responsible for the ReCharge API ("bootstrapheroes", ReCharge, or https://github.com/SocalProofit)

**Comment by sshaw** [comment]
Hi, this repository and account are not related to [ReCharge Payments](https://rechargepayments.com). This was made by [ScreenStaring](https://screenstaring.com).
