### ISSUE TITLE
how to use rake tasks for webhook

### ISSUE THREAD

**Issue by farooqch11** [ScreenStaring/recharge-api#3]
i am confused about using your rake tasks for creating hooks. 

-how can i call your tasks ? 
- where should i use these calls ?  i cannot call them rake yourtask 
-how to pass the parameters, address and topic of hook ?

**Comment by sshaw** [comment]
I've updated [the docs](https://github.com/ScreenStaring/recharge-api#rake-tasks-for-webhook-management), have a look and let me know if you have additional questions.
